"""empty message

Revision ID: 059880671a9b
Revises: d7f1cc83f353
Create Date: 2021-01-28 01:50:23.360075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '059880671a9b'
down_revision = 'd7f1cc83f353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'delivery_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('delivery_status', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
