"""empty message

Revision ID: 1f809dffaa40
Revises: 007b329e2b5f
Create Date: 2021-01-28 10:49:04.269769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f809dffaa40'
down_revision = '007b329e2b5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('active', sa.Boolean(), nullable=True))
    op.execute("UPDATE subscription SET active = FALSE")
    op.alter_column('subscription', 'active', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'active')
    # ### end Alembic commands ###
