"""empty message

Revision ID: 22b16074bc5f
Revises: 
Create Date: 2021-01-28 11:53:57.200331

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from app.main.model.notification import Notification

# revision identifiers, used by Alembic.
revision = '22b16074bc5f'
down_revision = None
branch_labels = None
depends_on = None
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('subscription_key', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('callback_url', sqlalchemy_utils.types.url.URLType(), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_update', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('callback_url'),
    sa.UniqueConstraint('subscription_key')
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=150), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_update', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('delivery_status', sqlalchemy_utils.types.choice.ChoiceType(Notification.DELIVERY_STATUS_TYPES), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    op.drop_table('subscription')
    # ### end Alembic commands ###
