"""empty message

Revision ID: 5dec42c71785
Revises: f8466b6b3c7e
Create Date: 2021-01-27 22:44:35.062489

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils import URLType


# revision identifiers, used by Alembic.
revision = '5dec42c71785'
down_revision = 'f8466b6b3c7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('callback_url', URLType(), nullable=False))
    op.create_unique_constraint(None, 'subscription', ['callback_url'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscription', type_='unique')
    op.drop_column('subscription', 'callback_url')
    # ### end Alembic commands ###
