"""empty message

Revision ID: fefca8113d96
Revises: 5dec42c71785
Create Date: 2021-01-27 23:06:46.973179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fefca8113d96'
down_revision = '5dec42c71785'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification', 'subscription_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification', 'subscription_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
